version: '3.8'

services:
  postgres:
    container_name: 'teacoder-nest.js'
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - teacoder-nest.js

volumes:
  postgres_data:

networks:
  teacoder-nest.js:
